/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import { customFetch } from '../../custom-fetch';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary Health Check
 */
export type healthCheckHealthGetResponse200 = {
  data: unknown
  status: 200
}
    
export type healthCheckHealthGetResponseSuccess = (healthCheckHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthCheckHealthGetResponse = (healthCheckHealthGetResponseSuccess)

export const getHealthCheckHealthGetUrl = () => {


  

  return `/health`
}

export const healthCheckHealthGet = async ( options?: RequestInit): Promise<healthCheckHealthGetResponse> => {
  
  return customFetch<healthCheckHealthGetResponse>(getHealthCheckHealthGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}




export const getHealthCheckHealthGetKey = () => [`/health`] as const;

export type HealthCheckHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheckHealthGet>>>
export type HealthCheckHealthGetQueryError = unknown

/**
 * @summary Health Check
 */
export const useHealthCheckHealthGet = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customFetch> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getHealthCheckHealthGetKey() : null);
  const swrFn = () => healthCheckHealthGet(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
