/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */

export interface CeleryQueueInfo {
  name: string;
  length: number;
  tasks: string[];
}
