/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { RedisKeysInfo } from './redisKeysInfo';

export type RedisStatusKeys = RedisKeysInfo | null;
