/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { RedisClientsInfo } from './redisClientsInfo';

export type RedisStatusClients = RedisClientsInfo | null;
