/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CeleryQueueInfo } from './celeryQueueInfo';
import type { CeleryTaskInfo } from './celeryTaskInfo';

export interface RedisCeleryInfo {
  default_queue: string;
  queues: CeleryQueueInfo[];
  registered_tasks: CeleryTaskInfo[];
}
