/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type { RedisStatusServer } from './redisStatusServer';
import type { RedisStatusClients } from './redisStatusClients';
import type { RedisStatusMemory } from './redisStatusMemory';
import type { RedisStatusKeys } from './redisStatusKeys';
import type { RedisStatusCelery } from './redisStatusCelery';
import type { RedisStatusError } from './redisStatusError';

export interface RedisStatus {
  url: string;
  connected: boolean;
  server?: RedisStatusServer;
  clients?: RedisStatusClients;
  memory?: RedisStatusMemory;
  keys?: RedisStatusKeys;
  celery?: RedisStatusCelery;
  error?: RedisStatusError;
}
