/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * FastAPI Backend
 * OpenAPI spec version: 0.1.0
 */
import type {
  Arguments,
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  HTTPValidationError,
  TriggerHelloTaskTasksHelloPostParams
} from '../../models';

import { customFetch } from '../../custom-fetch';


  
  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * Trigger a hello world task.
 * @summary Trigger Hello Task
 */
export type triggerHelloTaskTasksHelloPostResponse200 = {
  data: unknown
  status: 200
}

export type triggerHelloTaskTasksHelloPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type triggerHelloTaskTasksHelloPostResponseSuccess = (triggerHelloTaskTasksHelloPostResponse200) & {
  headers: Headers;
};
export type triggerHelloTaskTasksHelloPostResponseError = (triggerHelloTaskTasksHelloPostResponse422) & {
  headers: Headers;
};

export type triggerHelloTaskTasksHelloPostResponse = (triggerHelloTaskTasksHelloPostResponseSuccess | triggerHelloTaskTasksHelloPostResponseError)

export const getTriggerHelloTaskTasksHelloPostUrl = (params?: TriggerHelloTaskTasksHelloPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tasks/hello?${stringifiedParams}` : `/tasks/hello`
}

export const triggerHelloTaskTasksHelloPost = async (params?: TriggerHelloTaskTasksHelloPostParams, options?: RequestInit): Promise<triggerHelloTaskTasksHelloPostResponse> => {
  
  return customFetch<triggerHelloTaskTasksHelloPostResponse>(getTriggerHelloTaskTasksHelloPostUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getTriggerHelloTaskTasksHelloPostMutationFetcher = (params?: TriggerHelloTaskTasksHelloPostParams, options?: SecondParameter<typeof customFetch>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return triggerHelloTaskTasksHelloPost(params, options);
  }
}
export const getTriggerHelloTaskTasksHelloPostMutationKey = (params?: TriggerHelloTaskTasksHelloPostParams,) => [`/tasks/hello`, ...(params ? [params]: [])] as const;

export type TriggerHelloTaskTasksHelloPostMutationResult = NonNullable<Awaited<ReturnType<typeof triggerHelloTaskTasksHelloPost>>>
export type TriggerHelloTaskTasksHelloPostMutationError = HTTPValidationError

/**
 * @summary Trigger Hello Task
 */
export const useTriggerHelloTaskTasksHelloPost = <TError = HTTPValidationError>(
  params?: TriggerHelloTaskTasksHelloPostParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof triggerHelloTaskTasksHelloPost>>, TError, Key, Arguments, Awaited<ReturnType<typeof triggerHelloTaskTasksHelloPost>>> & { swrKey?: string }, request?: SecondParameter<typeof customFetch>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getTriggerHelloTaskTasksHelloPostMutationKey(params);
  const swrFn = getTriggerHelloTaskTasksHelloPostMutationFetcher(params, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
